### PR TITLE
fix(tests): Fixed and unified profit int. tests

### LINKED ISSUE #216: Profit integration tests fail when adding NLS to oracle's swap tree

### PR DESCRIPTION
**Pull request by KirilMihaylov**
Closes #216

### CODE REVIEW

File: tests/src/common/swap.rs [hunk 1]
```diff
@@ -17,6 +18,28 @@ use super::{
     ADMIN,
 };
 
+#[repr(transparent)]
+#[derive(Debug, Eq)]
+pub struct DexDenom<'r>(&'r str);
```
Comment (gmanev7) [inline tests/src/common/swap.rs:23]: could you outline the motivation behind your decision to define it?

**Review by gmanev7 — COMMENTED** [review]
The test functions are too long, resembling other tests in their previous state. Please review, extract the common code in functions, and reuse it.

File: tests/src/common/swap.rs (hunk 1 above)
Comment (KirilMihaylov) [reply tests/src/common/swap.rs:23]: So it is clear a DEX symbol is passed down and not a bank one. The whole motivation was to avoid ambiguity.

**Review by gmanev7 — APPROVED** [review]
